package io.novafoundation.nova.web3names.domain.exceptions

class ParseWeb3NameException : Exception()
